// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pbtmqhkwawmjqpayubkd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBidG1xaGt3YXdtanFwYXl1YmtkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1NTQwNjIsImV4cCI6MjA2ODEzMDA2Mn0.Z0CGNVovkwGSp0nSPq_wV7kJ3Rz18ijI-AlaIEiD-mo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});